### ISSUE TITLE
hash mismatch on 'nix develop'

### ISSUE THREAD

**Issue by microfirmware** [claudiomattera/esp32c3-embassy#2]
Hi, I'm getting the error below when running with `nix develop` on a clean checkout. Running in Ubuntu, latest version of nix installed from zero-to-nix. Appreciate any help.

`nix develop --show-trace
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/pkgs/stdenv/generic/make-derivation.nix:383:7:
          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       … while calling the 'getAttr' builtin
         at <nix/derivation-internal.nix>:44:19:
           43|       value = commonAttrs // {
           44|         outPath = builtins.getAttr outputName strict;
             |                   ^
           45|         drvPath = strict.drvPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'rust-stable'
         whose name attribute is located at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'paths' of derivation 'rust-stable'
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/combine.nix:10:16:
            9| symlinkJoin {
           10|   inherit name paths;
             |                ^
           11|   postBuild = ''

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:107:39:
          106|         let toolchain = fromToolchainName' target t.channel sha256; in
          107|         combine' "rust-${t.channel}" (attrVals
             |                                       ^
          108|           (filter (component: toolchain ? ${component}) (unique

       … while calling 'attrVals'
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:515:5:
          514|     nameList:
          515|     set: map (x: set.${x}) nameList;
             |     ^
          516|

       … while calling the 'map' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:515:10:
          514|     nameList:
          515|     set: map (x: set.${x}) nameList;
             |          ^
          516|

       … while calling the 'filter' builtin
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:108:12:
          107|         combine' "rust-${t.channel}" (attrVals
          108|           (filter (component: toolchain ? ${component}) (unique
             |            ^
          109|             (toolchain.manifest.profiles.${t.profile or "default"}

       … while calling the 'foldl'' builtin
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:108:58:
          107|         combine' "rust-${t.channel}" (attrVals
          108|           (filter (component: toolchain ? ${component}) (unique
             |                                                          ^
          109|             (toolchain.manifest.profiles.${t.profile or "default"}

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:106:25:
          105|       else
          106|         let toolchain = fromToolchainName' target t.channel sha256; in
             |                         ^
          107|         combine' "rust-${t.channel}" (attrVals

       … while calling 'fromToolchainName''
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:75:38:
           74|
           75|   fromToolchainName' = target: name: sha256:
             |                                      ^
           76|     mapNullable

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:76:5:
           75|   fromToolchainName' = target: name: sha256:
           76|     mapNullable
             |     ^
           77|       (matches:

       … while calling 'mapNullable'
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/trivial.nix:349:5:
          348|     f:
          349|     a: if a == null then a else f a;
             |     ^
          350|

       … from call site
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/trivial.nix:349:33:
          348|     f:
          349|     a: if a == null then a else f a;
             |                                 ^
          350|

       … while calling anonymous lambda
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:77:8:
           76|     mapNullable
           77|       (matches:
             |        ^
           78|         let target' = elemAt matches 5; in

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:79:9:
           78|         let target' = elemAt matches 5; in
           79|         toolchainOf' (if target' == null then target else target') {
             |         ^
           80|           inherit sha256;

       … while calling 'toolchainOf''
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:62:5:
           61|   toolchainOf' = target:
           62|     { root ? "https://static.rust-lang.org/dist"
             |     ^
           63|     , channel ? "nightly"

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:70:5:
           69|     in
           70|     fromManifestFile' target "-${channel}" (if (sha256 == null) then
             |     ^
           71|       builtins.fetchurl url

       … while calling 'fromManifestFile''
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:58:37:
           57|
           58|   fromManifestFile' = target: name: file:
             |                                     ^
           59|     fromManifest' target name (importTOML file);

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:59:5:
           58|   fromManifestFile' = target: name: file:
           59|     fromManifest' target name (importTOML file);
             |     ^
           60|

       … while calling 'fromManifest''
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:38:35:
           37|
           38|   fromManifest' = target: suffix: manifest:
             |                                   ^
           39|     let

       … in the left operand of the update (//) operator
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:49:15:
           48|     in
           49|     toolchain // mapAttrs'
             |               ^
           50|       (k: v:

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:40:19:
           39|     let
           40|       toolchain = mkToolchain suffix {
             |                   ^
           41|         inherit (manifest) date;

       … while calling anonymous lambda
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/mk-toolchain.nix:4:1:
            3| suffix:
            4| { date, components }:
             | ^
            5|

       … in the left operand of the update (//) operator
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/mk-toolchain.nix:159:13:
          158|
          159| toolchain'' // {
             |             ^
          160|   withComponents = componentNames: combine

       … in the left operand of the update (//) operator
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/mk-toolchain.nix:156:28:
          155|
          156|   toolchain'' = toolchain' // mapAttrs' (k: nameValuePair (removeSuffix "-preview" k)) toolchain';
             |                            ^
          157| in

       … in the left operand of the update (//) operator
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/mk-toolchain.nix:131:26:
          130|
          131|   toolchain' = toolchain // {
             |                          ^
          132|     toolchain = combine "rust${suffix}-${date}"

       … while calling the 'mapAttrs' builtin
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/lib/mk-toolchain.nix:15:15:
           14|
           15|   toolchain = mapAttrs
             |               ^
           16|     (component: source:

       … while calling the 'mapAttrs' builtin
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:42:22:
           41|         inherit (manifest) date;
           42|         components = mapAttrs
             |                      ^
           43|           (_: src: { inherit (src) url; sha256 = src.hash; })

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:44:12:
           43|           (_: src: { inherit (src) url; sha256 = src.hash; })
           44|           (filterAttrs (_: src: src ? available && src.available) (mapAttrs
             |            ^
           45|             (_: pkg: pkg.target."*" or pkg.target.${target} or null)

       … while calling 'filterAttrs'
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:646:5:
          645|     pred:
          646|     set:
             |     ^
          647|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … while calling the 'listToAttrs' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:647:5:
          646|     set:
          647|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |     ^
          648|

       … while calling the 'concatMap' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:647:18:
          646|     set:
          647|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                  ^
          648|

       … while calling the 'attrNames' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/attrsets.nix:647:114:
          646|     set:
          647|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                                                                                                                  ^
          648|

       … while calling the 'mapAttrs' builtin
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:44:68:
           43|           (_: src: { inherit (src) url; sha256 = src.hash; })
           44|           (filterAttrs (_: src: src ? available && src.available) (mapAttrs
             |                                                                    ^
           45|             (_: pkg: pkg.target."*" or pkg.target.${target} or null)

       … from call site
         at /nix/store/43r8l1jgq26kzza9kq4fpxngjspwf3rc-source/default.nix:59:32:
           58|   fromManifestFile' = target: name: file:
           59|     fromManifest' target name (importTOML file);
             |                                ^
           60|

       … while calling 'importTOML'
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/trivial.nix:730:16:
          729|   */
          730|   importTOML = path:
             |                ^
          731|     builtins.fromTOML (builtins.readFile path);

       … while calling the 'fromTOML' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/trivial.nix:731:5:
          730|   importTOML = path:
          731|     builtins.fromTOML (builtins.readFile path);
             |     ^
          732|

       … while evaluating the argument passed to builtins.fromTOML

       … while calling the 'readFile' builtin
         at /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/lib/trivial.nix:731:24:
          730|   importTOML = path:
          731|     builtins.fromTOML (builtins.readFile path);
             |                        ^
          732|

       … while realising the context of path '/nix/store/rfw29f6jpmklw802fi2qz7fs8jyx4ww8-channel-rust-stable.toml'

       error: hash mismatch in fixed-output derivation '/nix/store/8f9g26rrzjcv80w0dgv70xi8d0x57jgl-channel-rust-stable.toml.drv':
         specified: sha256-yMuSb5eQPO/bHv+Bcf/US8LVMbf/G/0MSfiPwBhiPpk=
            got:    sha256-s1RPtyvDGJaX/BisLT+ifVfuhDT1nZkZ1NcK8sbwELM=
`

**Comment by claudiomattera** [comment]
Unfortunately I do not use Nix, and I have no idea about this error or how to fix it.
The Nix flake was an external contribution.

@MaxKiv maybe do you have time to look into this?

**Comment by MaxKiv** [comment]
Ah my bad! It seems I failed to update the `rust-toolchain.toml` hash in `flake.nix`. In general this hash will have to be updated to convince nix to give you a devshell with the right toolchain. 

This feels odd, but it's a common pattern in the nix ecosystem. Nix has this annoying problem where it works really well if it gets to govern everything, but it feels unergonomic when it has to follow other version control systems (like the `rust-toolchain.toml`). 

It's nice to see that the horrible error messages have not changed 😂

In general when you want to parse nix errors, start from the bottom. Whenever you see something like `hash mismatch in fixed-output derivation` you can substitute the hash nix found.

Non nix users will never face these issues.

**Comment by MaxKiv** [comment]
See PR #3

**Comment by claudiomattera** [comment]
Thank you.
I will have a look at this tomorrow.

**Comment by claudiomattera** [comment]
I had a busier week than I expected, but now it should be merged in branch `v0.5.0-devel`.

@microfirmware If you could confirm it is working, I will make a new release with the new dependencies updated.
